[workspace]
members = [
  "crates/stdsimd-verify",
  "crates/stdsimd",
]

[profile.release]
debug = true
opt-level = 3

[profile.bench]
debug = 1
opt-level = 3

[profile.test]
opt-level = 0
lto = false
debug-assertions = true
codegen-units = 1
panic = 'unwind'