[target.mipsisa64r6-unknown-linux-gnuabi64.dependencies.std]
stage = 1
[target.mipsisa64r6-unknown-linux-gnuabi64.dependencies.core]
stage = 1
[target.mipsisa64r6-unknown-linux-gnuabi64.dependencies.panic_unwind]
stage = 0
[target.mipsisa64r6-unknown-linux-gnuabi64.dependencies.test]
stage = 2
[target.mipsisa64r6el-unknown-linux-gnuabi64.dependencies.std]
stage = 1
[target.mipsisa64r6el-unknown-linux-gnuabi64.dependencies.core]
stage = 1
[target.mipsisa64r6el-unknown-linux-gnuabi64.dependencies.panic_unwind]
stage = 0
[target.mipsisa64r6el-unknown-linux-gnuabi64.dependencies.test]
stage = 2
